name: Client Build using GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo '<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.GH_USERNAME }}</username>
                <password>${{ secrets.GH_PAT }}</password>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml

      - name: Build Client App
        run: mvn -f notification-client-app clean install -Dmaven.test.skip=true
